@url = http://localhost:3000


# @name CreateUnion
POST {{url}}/unions/api
Content-Type: application/json

{
  "unionName": {
      "properName": "United Farm Workers",
      "nickName": "UFW",
    },
   "locals":,
    "industry": "Agriculture",
    "website": "https://ufw.org",
    "contactInfo":
    {
      "phone": {
        "isTrue": true,
        "details": 6618236105
        },
     " eMail": {
        "isTrue": false,
        "details":
        },
      "faxLOL": {
        "isTrue": false,
        "details": ,
        },
      "address": {
        "isTrue": true,
        "details": 
          {"streetNumber": 220,
          "street": "18th St",
          "city": "Bakersfield",
          "State": "CA",
          "zip": 93301
        }
      }
    },
    "description":
  }
###

# @name GetProducts

GET {{url}}/

###

# @name SearchProducts
@productCode = {{GetProducts.response.body.0.UPC}}
GET {{url}}/{{productCode}}
###

# @name CreateProduct
POST {{url}}/
Content-Type: application/json

  {
  "UPC": 887227816615,
  "productName": "New fake product",
  "manufacturer": "Union Shop",
  "isUnion": true,
  "unionName": "WGA"
}
###

# @name UpdateProject
PATCH {{url}}/{{productCode}}
Content-Type: application/json

{
  "isUnion": false,
  "unionName": "N/A"
}

###

# @name DeleteProduct

DELETE {{url}}/{{productCode}}
###